# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
   config.vm.provision "shell", inline: "echo Iniciando aprovisionamiento"


   #Instalamos Web Servers - Apache
   (1..2).each do |i|
      config.vm.define "web-server-#{i}" do |web|
         web.vm.box="centos/7"
         web.vm.hostname= "web1"
         web.vm.network "public_network", ip: "192.168.1.9#{i}"
         web.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
         end   
         
         web.vm.provision "shell", path: "web_server.sh", :args => [i] 

      
      end
   end   

   #Instalamamos HA Proxy  
   config.vm.define "haproxy" do |ha|
      ha.vm.box="centos/7"
      ha.vm.hostname= "proxy"
      ha.vm.network "public_network", ip: "192.168.1.90"
      ha.vm.provider "virtualbox" do |v|
         v.memory = 1024
         v.cpus = 1
      end  
      
      ha.vm.provision "shell", path: "ha_proxy.sh"
    
   end

 
end
